/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import cloud.fastreport.model.CreateExportReportTaskVM;
import cloud.fastreport.model.CreateTransformTaskBaseVM;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePrepareTemplateTaskVM
 */
public class CreatePrepareTemplateTaskVMTest {
    private final CreatePrepareTemplateTaskVM model = new CreatePrepareTemplateTaskVM();

    /**
     * Model tests for CreatePrepareTemplateTaskVM
     */
    @Test
    public void testCreatePrepareTemplateTaskVM() {
        // TODO: test CreatePrepareTemplateTaskVM
    }

    /**
     * Test the property 'cronExpression'
     */
    @Test
    public void cronExpressionTest() {
        // TODO: test cronExpression
    }

    /**
     * Test the property 'delayedRunTime'
     */
    @Test
    public void delayedRunTimeTest() {
        // TODO: test delayedRunTime
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subscriptionId'
     */
    @Test
    public void subscriptionIdTest() {
        // TODO: test subscriptionId
    }

    /**
     * Test the property '$t'
     */
    @Test
    public void $tTest() {
        // TODO: test $t
    }

}
