/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import cloud.fastreport.model.DataSourceAdministrate;
import cloud.fastreport.model.DataSourceCreate;
import cloud.fastreport.model.DataSourceDelete;
import cloud.fastreport.model.DataSourceExecute;
import cloud.fastreport.model.DataSourceGet;
import cloud.fastreport.model.DataSourceUpdate;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for DataSourcePermission
 */
public class DataSourcePermissionTest {
    private final DataSourcePermission model = new DataSourcePermission();

    /**
     * Model tests for DataSourcePermission
     */
    @Test
    public void testDataSourcePermission() {
        // TODO: test DataSourcePermission
    }

    /**
     * Test the property 'create'
     */
    @Test
    public void createTest() {
        // TODO: test create
    }

    /**
     * Test the property 'delete'
     */
    @Test
    public void deleteTest() {
        // TODO: test delete
    }

    /**
     * Test the property 'execute'
     */
    @Test
    public void executeTest() {
        // TODO: test execute
    }

    /**
     * Test the property 'get'
     */
    @Test
    public void getTest() {
        // TODO: test get
    }

    /**
     * Test the property 'update'
     */
    @Test
    public void updateTest() {
        // TODO: test update
    }

    /**
     * Test the property 'administrate'
     */
    @Test
    public void administrateTest() {
        // TODO: test administrate
    }

}
