/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import cloud.fastreport.model.DataSourcePermissions;
import cloud.fastreport.model.FilePermissions;
import cloud.fastreport.model.GroupPermissions;
import cloud.fastreport.model.TaskPermissions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DefaultPermissionsVM
 */
public class DefaultPermissionsVMTest {
    private final DefaultPermissionsVM model = new DefaultPermissionsVM();

    /**
     * Model tests for DefaultPermissionsVM
     */
    @Test
    public void testDefaultPermissionsVM() {
        // TODO: test DefaultPermissionsVM
    }

    /**
     * Test the property 'filePermissions'
     */
    @Test
    public void filePermissionsTest() {
        // TODO: test filePermissions
    }

    /**
     * Test the property 'dataSourcePermissions'
     */
    @Test
    public void dataSourcePermissionsTest() {
        // TODO: test dataSourcePermissions
    }

    /**
     * Test the property 'groupPermissions'
     */
    @Test
    public void groupPermissionsTest() {
        // TODO: test groupPermissions
    }

    /**
     * Test the property 'taskPermissions'
     */
    @Test
    public void taskPermissionsTest() {
        // TODO: test taskPermissions
    }

}
