/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import cloud.fastreport.model.TransformTaskBaseVM;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrepareTemplateTaskVM
 */
public class PrepareTemplateTaskVMTest {
    private final PrepareTemplateTaskVM model = new PrepareTemplateTaskVM();

    /**
     * Model tests for PrepareTemplateTaskVM
     */
    @Test
    public void testPrepareTemplateTaskVM() {
        // TODO: test PrepareTemplateTaskVM
    }

    /**
     * Test the property 'cronExpression'
     */
    @Test
    public void cronExpressionTest() {
        // TODO: test cronExpression
    }

    /**
     * Test the property 'delayedRunTime'
     */
    @Test
    public void delayedRunTimeTest() {
        // TODO: test delayedRunTime
    }

    /**
     * Test the property 'delayedWasRunTime'
     */
    @Test
    public void delayedWasRunTimeTest() {
        // TODO: test delayedWasRunTime
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'recurrentRunTime'
     */
    @Test
    public void recurrentRunTimeTest() {
        // TODO: test recurrentRunTime
    }

    /**
     * Test the property 'recurrentWasRunTime'
     */
    @Test
    public void recurrentWasRunTimeTest() {
        // TODO: test recurrentWasRunTime
    }

    /**
     * Test the property 'subscriptionId'
     */
    @Test
    public void subscriptionIdTest() {
        // TODO: test subscriptionId
    }

    /**
     * Test the property '$t'
     */
    @Test
    public void $tTest() {
        // TODO: test $t
    }

}
