/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import cloud.fastreport.model.RunInputFileVM;
import cloud.fastreport.model.RunTaskBaseVM;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RunTransportTaskBaseVM
 */
public class RunTransportTaskBaseVMTest {
    private final RunTransportTaskBaseVM model = new RunTransportTaskBaseVM();

    /**
     * Model tests for RunTransportTaskBaseVM
     */
    @Test
    public void testRunTransportTaskBaseVM() {
        // TODO: test RunTransportTaskBaseVM
    }

    /**
     * Test the property 'subscriptionId'
     */
    @Test
    public void subscriptionIdTest() {
        // TODO: test subscriptionId
    }

    /**
     * Test the property '$t'
     */
    @Test
    public void $tTest() {
        // TODO: test $t
    }

}
