/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.model;

import java.util.Objects;
import java.util.Arrays;
import cloud.fastreport.model.TaskType;
import cloud.fastreport.model.TransportTaskBaseVM;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EmailTaskVM
 */
@JsonPropertyOrder({
  EmailTaskVM.JSON_PROPERTY_BODY,
  EmailTaskVM.JSON_PROPERTY_IS_BODY_HTML,
  EmailTaskVM.JSON_PROPERTY_SUBJECT,
  EmailTaskVM.JSON_PROPERTY_TO,
  EmailTaskVM.JSON_PROPERTY_FROM,
  EmailTaskVM.JSON_PROPERTY_USERNAME,
  EmailTaskVM.JSON_PROPERTY_SERVER,
  EmailTaskVM.JSON_PROPERTY_PORT,
  EmailTaskVM.JSON_PROPERTY_ENABLE_SSL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EmailTaskVM extends TransportTaskBaseVM {
  public static final String JSON_PROPERTY_BODY = "body";
  private JsonNullable<String> body = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_BODY_HTML = "isBodyHtml";
  private Boolean isBodyHtml;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  private JsonNullable<String> subject = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TO = "to";
  private JsonNullable<List<String>> to = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_FROM = "from";
  private JsonNullable<String> from = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USERNAME = "username";
  private JsonNullable<String> username = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SERVER = "server";
  private JsonNullable<String> server = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PORT = "port";
  private Integer port;

  public static final String JSON_PROPERTY_ENABLE_SSL = "enableSsl";
  private Boolean enableSsl;

  public EmailTaskVM() {

  }

  public EmailTaskVM body(String body) {
    this.body = JsonNullable.<String>of(body);
    
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getBody() {
        return body.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBody_JsonNullable() {
    return body;
  }
  
  @JsonProperty(JSON_PROPERTY_BODY)
  public void setBody_JsonNullable(JsonNullable<String> body) {
    this.body = body;
  }

  public void setBody(String body) {
    this.body = JsonNullable.<String>of(body);
  }


  public EmailTaskVM isBodyHtml(Boolean isBodyHtml) {
    
    this.isBodyHtml = isBodyHtml;
    return this;
  }

   /**
   * Get isBodyHtml
   * @return isBodyHtml
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_BODY_HTML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsBodyHtml() {
    return isBodyHtml;
  }


  @JsonProperty(JSON_PROPERTY_IS_BODY_HTML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsBodyHtml(Boolean isBodyHtml) {
    this.isBodyHtml = isBodyHtml;
  }


  public EmailTaskVM subject(String subject) {
    this.subject = JsonNullable.<String>of(subject);
    
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getSubject() {
        return subject.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSubject_JsonNullable() {
    return subject;
  }
  
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  public void setSubject_JsonNullable(JsonNullable<String> subject) {
    this.subject = subject;
  }

  public void setSubject(String subject) {
    this.subject = JsonNullable.<String>of(subject);
  }


  public EmailTaskVM to(List<String> to) {
    this.to = JsonNullable.<List<String>>of(to);
    
    return this;
  }

  public EmailTaskVM addToItem(String toItem) {
    if (this.to == null || !this.to.isPresent()) {
      this.to = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.to.get().add(toItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getTo() {
        return to.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTo_JsonNullable() {
    return to;
  }
  
  @JsonProperty(JSON_PROPERTY_TO)
  public void setTo_JsonNullable(JsonNullable<List<String>> to) {
    this.to = to;
  }

  public void setTo(List<String> to) {
    this.to = JsonNullable.<List<String>>of(to);
  }


  public EmailTaskVM from(String from) {
    this.from = JsonNullable.<String>of(from);
    
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getFrom() {
        return from.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFrom_JsonNullable() {
    return from;
  }
  
  @JsonProperty(JSON_PROPERTY_FROM)
  public void setFrom_JsonNullable(JsonNullable<String> from) {
    this.from = from;
  }

  public void setFrom(String from) {
    this.from = JsonNullable.<String>of(from);
  }


  public EmailTaskVM username(String username) {
    this.username = JsonNullable.<String>of(username);
    
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getUsername() {
        return username.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUsername_JsonNullable() {
    return username;
  }
  
  @JsonProperty(JSON_PROPERTY_USERNAME)
  public void setUsername_JsonNullable(JsonNullable<String> username) {
    this.username = username;
  }

  public void setUsername(String username) {
    this.username = JsonNullable.<String>of(username);
  }


  public EmailTaskVM server(String server) {
    this.server = JsonNullable.<String>of(server);
    
    return this;
  }

   /**
   * Get server
   * @return server
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public String getServer() {
        return server.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SERVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getServer_JsonNullable() {
    return server;
  }
  
  @JsonProperty(JSON_PROPERTY_SERVER)
  public void setServer_JsonNullable(JsonNullable<String> server) {
    this.server = server;
  }

  public void setServer(String server) {
    this.server = JsonNullable.<String>of(server);
  }


  public EmailTaskVM port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * minimum: 0
   * maximum: 2147483647
   * @return port
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(Integer port) {
    this.port = port;
  }


  public EmailTaskVM enableSsl(Boolean enableSsl) {
    
    this.enableSsl = enableSsl;
    return this;
  }

   /**
   * Get enableSsl
   * @return enableSsl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLE_SSL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnableSsl() {
    return enableSsl;
  }


  @JsonProperty(JSON_PROPERTY_ENABLE_SSL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableSsl(Boolean enableSsl) {
    this.enableSsl = enableSsl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailTaskVM emailTaskVM = (EmailTaskVM) o;
    return equalsNullable(this.body, emailTaskVM.body) &&
        Objects.equals(this.isBodyHtml, emailTaskVM.isBodyHtml) &&
        equalsNullable(this.subject, emailTaskVM.subject) &&
        equalsNullable(this.to, emailTaskVM.to) &&
        equalsNullable(this.from, emailTaskVM.from) &&
        equalsNullable(this.username, emailTaskVM.username) &&
        equalsNullable(this.server, emailTaskVM.server) &&
        Objects.equals(this.port, emailTaskVM.port) &&
        Objects.equals(this.enableSsl, emailTaskVM.enableSsl) &&
        super.equals(o);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(body), isBodyHtml, hashCodeNullable(subject), hashCodeNullable(to), hashCodeNullable(from), hashCodeNullable(username), hashCodeNullable(server), port, enableSsl, super.hashCode());
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailTaskVM {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    isBodyHtml: ").append(toIndentedString(isBodyHtml)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    enableSsl: ").append(toIndentedString(enableSsl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

