/*
 * FastReport Cloud
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.fastreport.client;

import org.junit.Test;
import org.junit.Ignore;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthCheckApi
 */
@Ignore
public class HealthCheckApiTest {

    private final HealthCheckApi api = new HealthCheckApi();

    
    /**
     * healthcheck
     *
     * 
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void healthCheckDataGetTest() throws IOException {
        api.healthCheckDataGet();

        // TODO: test validations
    }
    
}
